### ISSUE TITLE
joss-paper: Performance benchmarks

### ISSUE THREAD

**Issue by ericneiva** [baxmittens/DistributedSparseGrids.jl#6]
I think the software package (and the paper) will enormously benefit from a performance benchmark sustaining the performance claims of the software. I think this will also significantly increase the interest in the software and its impact. 

I would be very happy to see a plot "number of collocation points vs time", plotting the time required to generate increasingly refined grids for a given function (up to millions of collocation points).

But if you have a better idea for a performance benchmark, please go ahead.

See openjournals/joss-reviews#5003

**Comment by ericneiva** [comment]
Hi, @baxmittens, I really appreciate the effort you devoted to this.

I agree that a performance benchmark is not easy to include, so maybe I could do with a more elaborate and precise justification of your performance claim.

I've carefully read your results and discussion. I wonder if what sets this package apart from others and sustain your performance claim are the (1) distributed function evaluation and the (2) usage of arbitrary return types.

When evaluating a function at all grid points, while other packages exploit (at most) shared-memory parallelism, you can exploit distributed-memory parallelism. As a result, your package is clearly more suitable, when a single evaluation is computation- and memory-intensive.

Also, in contrast to other packages, the user can choose the right (performant) return data type for the problem at hand, optimise allocations with inplace operators...

Did I get this right?

**Comment by baxmittens** [comment]
@ericneiva 
A bit off-topic, but I just read some of your papers. They are very interesting to me. I also work on a similar topic. If you want to, you can check out our paper [an hp-hierarchical framework for the finite element exterior calculus](https://arxiv.org/abs/2012.15581) where we extended [natural refinement](http://www.multires.caltech.edu/pubs/Krysl-2002-CHARMS.pdf) (adaptive refinement without hanging nodes based on the refinement of basis function rather than elements) to arbitrary dimensions for all simplicial elements of [douglas n. arnolds finite element zoo](https://fenicsproject.org/pub/workshops/fenics13/slides/Arnold.pdf).

**Comment by baxmittens** [comment]
I added some subchapters to the paper. I close this for now and generate a paper proof in the review repo.
Reopen this if necessary.
